In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Review

In [2]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

**Review Question [1 min]**: Which one of the following two lines of code fail?

In [3]:
#cones.drop('Color').where('Color', 'pink')

In [4]:
cones.where('Color', 'pink').drop('Color')

Flavor     | Price
strawberry | 3.55
strawberry | 5.25
bubblegum  | 4.75

## New material

### `int` and `float`

In [5]:
1 + 3 

4

In [6]:
1234567 * 890

1098764630

In [7]:
1234567 ** 20

67653969256331495649068283811346298491907584134058827077138045699295881910674491882264924512105825607973877575534562149601

____

In [8]:
2024

2024

In [9]:
1012 * 2

2024

In [10]:
4048/2

2024.0

_______

#### `floats` have some limitations

In [11]:
10/3

3.3333333333333335

In [12]:
75892745.215489247589274985712

75892745.21548925

In [13]:
75892745.215489247589274985712 - 75892745.21548925

0.0

____

In [14]:
(13 ** 0.5) 

3.605551275463989

In [15]:
(13 ** 0.5) ** 2

12.999999999999998

____

In [16]:
(1234567 ** 20)/1

6.765396925633149e+121

### Strings are snippets of text

In [17]:
'Flavor'

'Flavor'

In [18]:
#Flavor

In [19]:
#'I wouldn't ever ignore my homework'

In [20]:
"I wouldn't ever ignore my homework"

"I wouldn't ever ignore my homework"

________

In [21]:
"I" + "wouldn't ever ignore my homework"

"Iwouldn't ever ignore my homework"

In [22]:
"I" + " wouldn't ever ignore my homework"

"I wouldn't ever ignore my homework"

In [23]:
"Ben" + " 10"

'Ben 10'

In [24]:
#"Ben" + 10

In [25]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

### You can convert between types

In [26]:
int('3')

3

In [27]:
int(float('3.0'))

3

In [28]:
float(int('3'))

3.0

In [29]:
str(10)

'10'

In [30]:
'Ben ' + str(10)

'Ben 10'

In [31]:
2 + float(8)

10.0

### ... but be careful!

In [32]:
#float('one point two')

In [33]:
int(1.2)

1

In [34]:
int(1.23)

1

In [35]:
round(1.23, ndigits = 1)

1.2

In [36]:
int(1.6)

1

In [37]:
round(1.6)

2

_____

### Every value has a **data type**

In [38]:
type(10)

int

In [39]:
a = 10

In [40]:
type(a)

int

In [41]:
type(1012*2)

int

In [42]:
type(4048/2)

float

In [43]:
type('Ben')

str

In [44]:
type('Ben ' + str(10))

str

In [45]:
type(abs)

builtin_function_or_method

_____

#### This includes tables and columns of tables!

In [46]:
nba = Table.read_table('nba_salaries.csv')
type(nba)

datascience.tables.Table

In [47]:
nba.show(6)

In [48]:
nba.sort('season', descending=True).show(6)

In [49]:
nba.select('salary')

salary
17142000
16806000
15004000
15000000
14795000
14000000
11910000
11020000
10800000
10780000
... (9446 rows omitted)

In [50]:
type(nba.select('salary'))

datascience.tables.Table

In [51]:
nba.column('salary')

array([17142000, 16806000, 15004000, ...,   183115,   183115,   155647])

In [52]:
type(nba.column('salary'))

numpy.ndarray

#### **Arrays** are sequences of values

In [53]:
my_array = make_array(1, 2, 3, 4)

In [54]:
my_array

array([1, 2, 3, 4])

In [55]:
type(my_array)

numpy.ndarray

In [56]:
my_array.item(1)

2

In [57]:
my_array.item(0)

1

In [58]:
#my_array.item(4)

____

In [59]:
my_array + 2

array([3, 4, 5, 6])

In [60]:
my_array * 2

array([2, 4, 6, 8])

In [61]:
my_array ** 2

array([ 1,  4,  9, 16])

In [62]:
my_array_2 = make_array(4,5,6,7)

In [63]:
my_array + my_array_2

array([ 5,  7,  9, 11])

In [64]:
#my_array + make_array(8,9,10)

In [65]:
#my_array * make_array(8,9,10)

#### Functions on arrays

In [66]:
my_array = make_array(1, 2, 3, 4)

In [67]:
sum(my_array)

10

In [68]:
np.average(my_array)

2.5

In [69]:
len(my_array)

4

##### Remember that a column of a table is an array!

In [70]:
np.average(nba.column('salary'))

4486115.181154822

_____

### Ranges are sequences of consecutive numbers

In [71]:
make_array(0,1,2,3,4,5,6)

array([0, 1, 2, 3, 4, 5, 6])

In [72]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [73]:
np.arange(stop=7)

array([0, 1, 2, 3, 4, 5, 6])

In [74]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [75]:
np.arange(start=0, stop=7, step=3)

array([0, 3, 6])

In [76]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [77]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [78]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])